server:
  port: 8081

spring:
  application:
    name: spring-jms-demo

amqp:
  host: localhost
  username: guest
  password: guest
  queue: myqueue
  # DO NOT SET THIS 'true' IN PRODUCTION!
  trustAllCerts: true