spring:
  application:
    name: spring-jms-demo

amqp:
  host: localhost
  username: guest
  password: guest
  # Simple queue
  queue: myqueue
  # Topic and subscription:
  topic: test.topic
  subscription: test.queue
  # DO NOT SET THIS 'true' IN PRODUCTION!
  trustAllCerts: true
  # You only need this to be non-zero for build pipeline
  startDelaySeconds: 30